import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Layout } from "@/components/Layout";
import profilePic from "../../public/images/profile/me-developr.png";
import { AnimatedText } from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="bg-white dark:bg-gradient-to-br dark:from-slate-900 dark:via-slate-950 dark:to-black w-full min-h-screen">
      <Head>
        <title>My Portfolio | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex items-center justify-center flex-col w-full min-h-screen">
        <Layout className="pt-0 px-6 py-8">
          <div className="flex flex-col lg:flex-row items-center justify-between w-full">
            {/* Image */}
            <div className="w-full lg:w-1/2 flex justify-center mb-8 lg:mb-0">
              <Image
                src={profilePic}
                alt="me"
                className="w-72 md:w-96 h-auto transform scale-x-[-1] rounded-xl"
              />
            </div>

            {/* Text */}
            <div className="w-full lg:w-1/2 flex flex-col items-center lg:items-start">
              <AnimatedText
                text="Turning Vision into Reality with Code And Design"
                className="!text-4xl md:!text-5xl lg:!text-6xl text-center lg:text-left"
              />
              <p className="my-4 text-base font-light text-center lg:text-left text-dark dark:text-light">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex flex-col sm:flex-row items-center mt-4">
                <Link
                  href="/resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light px-6 py-2 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark transition duration-500"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-2"} />
                </Link>
                <Link
                  href={`mailto:${process.env.NEXT_PUBLIC_EMAIL}`}
                  target={"_blank"}
                  className="ml-0 sm:ml-4 mt-4 sm:mt-0 text-lg font-medium capitalize text-dark dark:text-light underline"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </div>
  );
}
